### ISSUE TITLE
请教下如何使用？

### ISSUE THREAD

**Issue by yandong31** [shaonianzhentan/conversation#1]
我把插件放入custom_components，然后在配置文件中加入conversation:  插件正常载入了，但是语音交互只能识别成英文，text: 语音文本也是空的，没有任何显示，在事件中也找不到ha_voice_text_event， 还需要什么设置吗？

之前在交互界面输入文本命令还是可以执行的，比如“打开客厅灯”。我升级18.4后，文本命令也能执行了，提示正在打开客厅灯，但实际没作用。

**Comment by shaonianzhentan** [comment]
> 我把插件放入custom_components，然后在配置文件中加入conversation: 插件正常载入了，但是语音交互只能识别成英文，text: 语音文本也是空的，没有任何显示，在事件中也找不到ha_voice_text_event， 还需要什么设置吗？
> 
> 之前在交互界面输入文本命令还是可以执行的，比如“打开客厅灯”。我升级18.4后，文本命令也能执行了，提示正在打开客厅灯，但实际没作用。

你下载master版本试试，我正在开发新功能

**Comment by yandong31** [comment]
感谢回复，我就是直接下的master ，要不我换成relase的试试， 开启方式对了吗？ 没有其他参数要设置吧。

**Comment by shaonianzhentan** [comment]
> 感谢回复，我就是直接下的master ，要不我换成relase的试试， 开启方式对了吗？ 没有其他参数要设置吧。



> 感谢回复，我就是直接下的master ，要不我换成relase的试试， 开启方式对了吗？ 没有其他参数要设置吧。

运行时看日志吧
