### ISSUE TITLE
ha core 12.0报错

### ISSUE THREAD

**Issue by goxofy** [shaonianzhentan/conversation#12]
Component error: conversation - cannot import name 'HTTP_INTERNAL_SERVER_ERROR' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by shaonianzhentan** [comment]
你用的什么版本？

**Comment by goxofy** [comment]
home assistant os

core版本昨天升级了12.0，然后这个组件就报错了

**Comment by shaonianzhentan** [comment]
我说的是你用的组件版本

**Comment by goxofy** [comment]
是1.5

**Comment by shaonianzhentan** [comment]
那你升级啊

**Comment by goxofy** [comment]
我是用hacs安装的，貌似没新版，只能手动安装1.55么

**Comment by shaonianzhentan** [comment]
安装master版本

**Comment by goxofy** [comment]
ok
