### ISSUE TITLE
今年会增加控制种类吗？

### ISSUE THREAD

**Issue by ritech** [shaonianzhentan/conversation#20]
窗帘，空调，地暖，灯光，风扇，洗衣机啥的

**Comment by shaonianzhentan** [comment]
> 窗帘，空调，地暖，灯光，风扇，洗衣机啥的

基本都支持，高级功能可以自定义适配

**Comment by ritech** [comment]
看了官方今年也主推语音控制，如果能本地控制，真是可以在内网断网执行了，太方便了
后面就看怎么把小爱 或者 天猫的语音完全接入到ha
