### ISSUE TITLE
button 无法用语音启用

### ISSUE THREAD

**Issue by ritech** [shaonianzhentan/conversation#23]
script 是可以的

**Comment by shaonianzhentan** [comment]
> script 是可以的

你说：**触发`按钮的名称`**，不行么？

**Comment by ritech** [comment]
ok了，不过读触发有点怪，不如直接读打开 关闭简单

**Comment by ritech** [comment]
目前用ios下面的home assistant app，通过快捷指令，语音输入，发现apple的语音是真的不够智能，触发 变成 出发，次卫变成刺猬

**Comment by shaonianzhentan** [comment]
> ok了，不过读触发有点怪，不如直接读打开 关闭简单

按钮没有`打开/关闭`的概念，推荐用脚本

**Comment by shaonianzhentan** [comment]
> 目前用ios下面的home assistant app，通过快捷指令，语音输入，发现apple的语音是真的不够智能，触发 变成 出发，次卫变成刺猬

可以使用微信控制，将小程序添加到桌面，直接输入文本进行控制

**Comment by ritech** [comment]
明白了，感觉area选项有点难受，我有部分mqtt switch是在config yaml定义的，无法选择区域，比如关闭卧室所有的灯，就没办法判断区域

**Comment by shaonianzhentan** [comment]
> 明白了，感觉area选项有点难受，我有部分mqtt switch是在config yaml定义的，无法选择区域，比如关闭卧室所有的灯，就没办法判断区域

这种操作建议自定义指令，比如新建一个`关闭卧室所有的灯=关闭卧室所有灯`的脚本，然后在脚本里配置相关服务，这样可控性更强

**Comment by ritech** [comment]
我想在node red直接获取文本 ，然后触发指令
目前好像抓不到
![2023e26755b9a8481a95312bf88a1570](https://user-images.githubusercontent.com/11290395/225259872-d05830a9-1cff-4666-939f-820c9b53060a.png)

是要用events all获取吗？

**Comment by shaonianzhentan** [comment]
> 我想在node red直接获取文本 ，然后触发指令 目前好像抓不到 ![2023e26755b9a8481a95312bf88a1570](https://user-images.githubusercontent.com/11290395/225259872-d05830a9-1cff-4666-939f-820c9b53060a.png)
> 
> 是要用events all获取吗？

你可以监听`conversation`事件，获取`text`属性

**Comment by shaonianzhentan** [comment]
button按钮在新版中支持直接触发了
