### ISSUE TITLE
升级2023.5.2后hacs下载该插件后如下图升级2023.5.2后hacs下载该插件后如下图

### ISSUE THREAD

**Issue by Gzzloveyyt** [shaonianzhentan/conversation#24]
升级2023.5.2后hacs下载该插件后如下图
![image](https://user-images.githubusercontent.com/25847375/236790481-d7e541af-f107-42e9-9970-c8af1eb807af.png)

**Comment by shaonianzhentan** [comment]
网络问题，正在下载依赖

**Comment by cstackess** [comment]
带输入参数的脚该怎么触发？

**Comment by popweiok** [comment]
我也遇到了，没转两圈就提示
![image](https://github.com/shaonianzhentan/conversation/assets/117420966/db2328e3-0f5b-4771-a087-d2ac965e3348)

**Comment by shaonianzhentan** [comment]
> 我也遇到了，没转两圈就提示 ![image](https://user-images.githubusercontent.com/117420966/239459965-db2328e3-0f5b-4771-a087-d2ac965e3348.png)

看错误日志，有依赖需要下载，可以重启HA再试
