### ISSUE TITLE
升级core之后，配置报错，删除报错

### ISSUE THREAD

**Issue by luckywaa** [shaonianzhentan/conversation#30]
![image](https://github.com/shaonianzhentan/conversation/assets/8738803/c8fa0a7a-c2b6-47ed-852e-a22b33bf05e8)

![image](https://github.com/shaonianzhentan/conversation/assets/8738803/21f00678-175d-4537-9685-874f87aeb5b9)

本来想重新导入一下，发现不行

**Comment by shaonianzhentan** [comment]
已修复
