### ISSUE TITLE
安装不上，怎么办好呢

### ISSUE THREAD

**Issue by lj4o7** [shaonianzhentan/conversation#32]
我是下载的压缩包手动放进custom_components目录的，重启ha搜到语音小助手集成，但安装时弹出以下提示：

错误
无法加载配置向导: {"message":"Invalid handler specified"}

我已经试过清理浏览器cookie。

**Comment by shaonianzhentan** [comment]
HA的版本新吗？最好贴一下相关的错误日志

**Comment by lj4o7** [comment]
大佬，我是用hyper-v虚拟机装的haos，日志里相关错误提示如下：
Logger: homeassistant.config_entries
Source: config_entries.py:2087
First occurred: 11:26:59 (5 occurrences)
Last logged: 11:40:47

Error occurred loading flow for integration conversation_assistant: cannot import name 'get_languages' from 'home_assistant_intents' (/usr/local/lib/python3.11/site-packages/home_assistant_intents/__init__.py)

**Comment by lj4o7** [comment]
Home Assistant

Core    2024.1.2
Supervisor    2024.05.1
Operating System    11.3
Frontend    20240104.0

**Comment by shaonianzhentan** [comment]
最低版本要求是2024.2.0，你HA的版本太低了

**Comment by lj4o7** [comment]
谢谢大佬，更新core后安装成功。
