### ISSUE TITLE
home assistant 2024.08 已经不支持语音助手对话框

### ISSUE THREAD

**Issue by ritech** [shaonianzhentan/conversation#33]
![QQ_1723502714448](https://github.com/user-attachments/assets/6ccd4081-4ba9-4ac2-a274-01d93ae5435f)

提示 此助手无法控制您的家
并且交流无任何回复
![QQ_1723502464048](https://github.com/user-attachments/assets/94da5c19-4a81-45a2-bfe3-cc680dc434e2)

但是通过调试管道，能看到回复 ，并且支持控制
![QQ_1723502644249](https://github.com/user-attachments/assets/95dc0826-2503-4466-988c-0874c0c2edb5)

**Comment by shaonianzhentan** [comment]
已适配
