### ISSUE TITLE
init 文件 DOMAIN 配置正常 configuration 无法识别 hello_miai

### ISSUE THREAD

**Issue by ten-ltw** [shaonianzhentan/conversation#8]
哈喽入坑新手，没有找到 py 的开发文档。

我这边在 `hello_miai/__init__.py` 中看到了 `DOMAIN = 'hello_miai'`，重启后 integration 中能够找到已经安装的 hello miai。

但是我在 configuration 中配置
```
hello_miai:
  miid: '13123456789'
  password: 'password'
```
时，check 插件提示我 `hello_miai - Integration 'hello_miai' not found.`。

同样自己写的 py 也遇到了同样的情况，不知道您是否有经验这个是哪里的问题？
我现在有点当局者迷，望赐教感激不尽。

**Comment by shaonianzhentan** [comment]
这是官方开发文档：https://hass.dev/
